import Head from 'next/head'
import { Header } from '../components/organisms/Header'
import { PageHome } from '../components/pages/home'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <PageHome />
    </>
  )
}
